#include <stdio.h>
#include <string.h>

int base64_encode(const unsigned char *in, int inLen, char *out)
{
    static const char *ENC =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    char *original_out = out;

    while (inLen) {
        // first 6 bits of char 1
        *out++ = ENC[*in >> 2];
        if (!--inLen) {
            // last 2 bits of char 1, 4 bits of 0
            *out++ = ENC[(*in & 0x3) << 4];
            *out++ = '=';
            *out++ = '=';
            break;
        }
        // last 2 bits of char 1, first 4 bits of char 2
        *out++ = ENC[((*in & 0x3) << 4) | (*(in + 1) >> 4)];
        in++;
        if (!--inLen) {
            // last 4 bits of char 2, 2 bits of 0
            *out++ = ENC[(*in & 0xF) << 2];
            *out++ = '=';
            break;
        }
        // last 4 bits of char 2, first 2 bits of char 3
        *out++ = ENC[((*in & 0xF) << 2) | (*(in + 1) >> 6)];
        in++;
        // last 6 bits of char 3
        *out++ = ENC[*in & 0x3F];
        in++, inLen--;
    }

    return (int)(out - original_out);
}

int base64_decode(unsigned char *code)  
{  
//根据base64表，以字符找到对应的十进制数据  
    static const int table[]={
		0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,62,0,0,0,
		63,52,53,54,55,56,57,58,
		59,60,61,0,0,0,0,0,0,0,0,
		1,2,3,4,5,6,7,8,9,10,11,12,
		13,14,15,16,17,18,19,20,21,
		22,23,24,25,0,0,0,0,0,0,26,
		27,28,29,30,31,32,33,34,35,
		36,37,38,39,40,41,42,43,44,
		45,46,47,48,49,50,51
	};  
    long len;  
    long outlen;  
    int i,j;  
  
//计算解码后的字符串长度  
    len=strlen((char *)code);  
//判断编码后的字符串后是否有=  
    if(strstr((char *)code,"=="))  
        outlen=len/4*3-2;  
    else if(strstr((char *)code,"="))  
        outlen=len/4*3-1;  
    else  
        outlen=len/4*3;  
  
//以4个字符为一位进行解码  
    for(i=0,j=0; i < len-2; j+=3,i+=4)  
    {  
        code[j]=((unsigned char)table[code[i]])<<2 | (((unsigned char)table[code[i+1]])>>4); //取出第一个字符对应base64表的十进制数的前6位与第二个字符对应base64表的十进制数的后2位进行组合  
        code[j+1]=(((unsigned char)table[code[i+1]])<<4) | (((unsigned char)table[code[i+2]])>>2); //取出第二个字符对应base64表的十进制数的后4位与第三个字符对应bas464表的十进制数的后4位进行组合  
        code[j+2]=(((unsigned char)table[code[i+2]])<<6) | ((unsigned char)table[code[i+3]]); //取出第三个字符对应base64表的十进制数的后2位与第4个字符进行组合  
    }  
  
	return outlen;
}

int main(void)
{
	int num = 0, len = 0;
	char str[] = "Hello wor";
	unsigned char buf[1024];
	
	num = base64_encode((unsigned char*)str, strlen(str), (char *)buf);
	buf[num] = '\0';
	printf("%s\n", buf);
	
	len = base64_decode(buf);
	buf[len] = '\0';
	printf("[%s]\n", buf);

	unsigned char bbuf[]={
"f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAQAUAAAAAAABAAAAAAAAAADAZAAAAAAAAAAAAAEAAOAAJAEAAHQAcAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA+AEAAAAAAAD4AQAAAAAAAAgAAAAAAAAAAwAAAAQAAAA4AgAAAAAAADgCAAAAAAAAOAIAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAKAAAAAAAAUAoAAAAAAAAAACAAAAAAAAEAAAAGAAAAuA0AAAAAAAC4DSAAAAAAALgNIAAAAAAAWAIAAAAAAABgAgAAAAAAAAAAIAAAAAAAAgAAAAYAAADIDQAAAAAAAMgNIAAAAAAAyA0gAAAAAADwAQAAAAAAAPABAAAAAAAACAAAAAAAAAAEAAAABAAAAFQCAAAAAAAAVAIAAAAAAABUAgAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFDldGQEAAAACAkAAAAAAAAICQAAAAAAAAgJAAAAAAAAPAAAAAAAAAA8AAAAAAAAAAQAAAAAAAAAUeV0ZAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABS5XRkBAAAALgNAAAAAAAAuA0gAAAAAAC4DSAAAAAAAEgCAAAAAAAASAIAAAAAAAABAAAAAAAAAC9saWI2NC9sZC1saW51eC14ODYtNjQuc28uMgAEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAQAAAAUAAAAAwAAAEdOVQCnHLMZEKlKGxbNb2tldSd0F8ABfQEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAACAAAAAAAAAAAAAAAAAAAAAAAAAACwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAIQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAWwAAACAAAAAAAAAAAAAAAAAAAAAAAAAAagAAACAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAGxpYmMuc28uNgBwcmludGYAX19jeGFfZmluYWxpemUAX19saWJjX3N0YXJ0X21haW4AR0xJQkNfMi4yLjUAX0lUTV9kZXJlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fZ21vbl9zdGFydF9fAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAAAAAAAIAAgAAAAAAAgAAAAAAAAABAAEAAQAAABAAAAAAAAAAdRppCQAAAgAzAAAAAAAAALgNIAAAAAAACAAAAAAAAABABgAAAAAAAMANIAAAAAAACAAAAAAAAAAABgAAAAAAAAgQIAAAAAAACAAAAAAAAAAIECAAAAAAANgPIAAAAAAABgAAAAEAAAAAAAAAAAAAAOAPIAAAAAAABgAAAAMAAAAAAAAAAAAAAOgPIAAAAAAABgAAAAQAAAAAAAAAAAAAAPAPIAAAAAAABgAAAAUAAAAAAAAAAAAAAPgPIAAAAAAABgAAAAYAAAAAAAAAAAAAANAPIAAAAAAABwAAAAIAAAAAAAAAAAAAAEiD7AhIiwXtCiAASIXAdAL/0EiDxAjDAAAAAAAAAAAA/zWqCiAA/yWsCiAADx9AAP8lqgogAGgAAAAA6eD/////JcIKIABmkAAAAAAAAAAAMe1JidFeSIniSIPk8FBUTI0FqgIAAEiNDTMCAABIjT3mAAAA/xV2CiAA9A8fRAAASI09mQogAFVIjQWRCiAASDn4SInldBlIiwVKCiAASIXAdA1d/+BmLg8fhAAAAAAAXcMPH0AAZi4PH4QAAAAAAEiNPVkKIABIjTVSCiAAVUgp/kiJ5UjB/gNIifBIweg/SAHGSNH+dBhIiwURCiAASIXAdAxd/+BmDx+EAAAAAABdww8fQABmLg8fhAAAAAAAgD0JCiAAAHUvSIM95wkgAABVSInldAxIiz3qCSAA6A3////oSP///8YF4QkgAAFdww8fgAAAAADzw2YPH0QAAFVIieVd6Wb///9VSInlSIPsIEjHwv////9Ix8b/////SI09sQEAALgAAAAA6K/+//+6/////77/////SI09rwEAALgAAAAA6JT+//+6//8AAL7//wAASI09qwEAALgAAAAA6Hn+//+6/wAAAL7/AAAASI09pwEAALgAAAAA6F7+//9IugAAAAAAAACASL4AAAAAAAAAgEiNPZgBAAC4AAAAAOg5/v//ugAAAIC+AAAAgEiNPZUBAAC4AAAAAOge/v//ugCA//++AID//0iNPZABAAC4AAAAAOgD/v//uoD///++gP///0iNPYsBAAC4AAAAAOjo/f//SIsFuQEAAEiJRejyDxBF6EiNPX8BAAC4AQAAAOjH/f//SIsFoAEAAEiJRejyDxBF6EiNPXABAAC4AQAAAOim/f//SMdF+AAAAABIi0X4xgBjuAAAAADJw0FXQVZJiddBVUFUTI0lFgYgAFVIjS0WBiAAU0GJ/UmJ9kwp5UiD7AhIwf0D6C/9//9Ihe10IDHbDx+EAAAAAABMifpMifZEie9B/xTcSIPDAUg53XXqSIPECFtdQVxBXUFeQV/DkGYuDx+EAAAAAADzwwAASIPsCEiDxAjDAAAAAQACAAAAAABVSU5UNjRfTUFYOlslbGRdWzB4JWx4XQoAVUlOVDMyX01BWDpbJWRdWzB4JXhdCgBVSU5UMTZfTUFYOlslZF1bMHgleF0KAFVJTlQ4X01BWDpbJWRdWzB4JXhdCgBJTlQ2NF9NSU46WyVsZF1bMHglbHhdCgBJTlQzMl9NSU46WyVkXVsweCV4XQoASU5UMTZfTUlOOlslZF1bMHgleF0KAElOVDhfTUlOOlslZF1bMHgleF0KAGZsb2F0MzIgTUFYOlslZl0KAGRvdWJsZSA2NCBNQVg6WyVmXQoAAAAAAAAAAOD//+9H////////738BGwM7PAAAAAYAAAAI/P//iAAAACj8//+wAAAAOPz//1gAAABC/f//yAAAAIj+///oAAAA+P7//zABAAAAAAAAFAAAAAAAAAABelIAAXgQARsMBwiQAQcQFAAAABwAAADY+///KwAAAAAAAAAAAAAAFAAAAAAAAAABelIAAXgQARsMBwiQAQAAJAAAABwAAAB4+///IAAAAAAOEEYOGEoPC3cIgAA/GjsqMyQiAAAAABQAAABEAAAAcPv//wgAAAAAAAAAAAAAABwAAABcAAAAcvz//0YBAAAAQQ4QhgJDDQYDQQEMBwgARAAAAHwAAACY/f//ZQAAAABCDhCPAkIOGI4DRQ4gjQRCDiiMBUgOMIYGSA44gwdNDkByDjhBDjBBDihCDiBCDhhCDhBCDggAEAAAAMQAAADA/f//AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABgAAAAAAAAAGAAAAAAAAAQAAAAAAAAABAAAAAAAAAAwAAAAAAAAA8AQAAAAAAAANAAAAAAAAAAQIAAAAAAAAGQAAAAAAAAC4DSAAAAAAABsAAAAAAAAACAAAAAAAAAAaAAAAAAAAAMANIAAAAAAAHAAAAAAAAAAIAAAAAAAAAPX+/28AAAAAmAIAAAAAAAAFAAAAAAAAAGADAAAAAAAABgAAAAAAAAC4AgAAAAAAAAoAAAAAAAAAhAAAAAAAAAALAAAAAAAAABgAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAuA8gAAAAAAACAAAAAAAAABgAAAAAAAAAFAAAAAAAAAAHAAAAAAAAABcAAAAAAAAA2AQAAAAAAAAHAAAAAAAAABgEAAAAAAAACAAAAAAAAADAAAAAAAAAAAkAAAAAAAAAGAAAAAAAAAAeAAAAAAAAAAgAAAAAAAAA+///bwAAAAABAAAIAAAAAP7//28AAAAA+AMAAAAAAAD///9vAAAAAAEAAAAAAAAA8P//bwAAAADkAwAAAAAAAPn//28AAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMgNIAAAAAAAAAAAAAAAAAAAAAAAAAAAACYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBAgAAAAAABHQ0M6IChVYnVudHUgNy41LjAtM3VidW50dTF+MTguMDQpIDcuNS4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABADgCAAAAAAAAAAAAAAAAAAAAAAAAAwACAFQCAAAAAAAAAAAAAAAAAAAAAAAAAwADAHQCAAAAAAAAAAAAAAAAAAAAAAAAAwAEAJgCAAAAAAAAAAAAAAAAAAAAAAAAAwAFALgCAAAAAAAAAAAAAAAAAAAAAAAAAwAGAGADAAAAAAAAAAAAAAAAAAAAAAAAAwAHAOQDAAAAAAAAAAAAAAAAAAAAAAAAAwAIAPgDAAAAAAAAAAAAAAAAAAAAAAAAAwAJABgEAAAAAAAAAAAAAAAAAAAAAAAAAwAKANgEAAAAAAAAAAAAAAAAAAAAAAAAAwALAPAEAAAAAAAAAAAAAAAAAAAAAAAAAwAMABAFAAAAAAAAAAAAAAAAAAAAAAAAAwANADAFAAAAAAAAAAAAAAAAAAAAAAAAAwAOAEAFAAAAAAAAAAAAAAAAAAAAAAAAAwAPAAQIAAAAAAAAAAAAAAAAAAAAAAAAAwAQABAIAAAAAAAAAAAAAAAAAAAAAAAAAwARAAgJAAAAAAAAAAAAAAAAAAAAAAAAAwASAEgJAAAAAAAAAAAAAAAAAAAAAAAAAwATALgNIAAAAAAAAAAAAAAAAAAAAAAAAwAUAMANIAAAAAAAAAAAAAAAAAAAAAAAAwAVAMgNIAAAAAAAAAAAAAAAAAAAAAAAAwAWALgPIAAAAAAAAAAAAAAAAAAAAAAAAwAXAAAQIAAAAAAAAAAAAAAAAAAAAAAAAwAYABAQIAAAAAAAAAAAAAAAAAAAAAAAAwAZAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAMAAAAAgAOAHAFAAAAAAAAAAAAAAAAAAAOAAAAAgAOALAFAAAAAAAAAAAAAAAAAAAhAAAAAgAOAAAGAAAAAAAAAAAAAAAAAAA3AAAAAQAYABAQIAAAAAAAAQAAAAAAAABGAAAAAQAUAMANIAAAAAAAAAAAAAAAAABtAAAAAgAOAEAGAAAAAAAAAAAAAAAAAAB5AAAAAQATALgNIAAAAAAAAAAAAAAAAACYAAAABADx/wAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAChAAAAAQASAEwKAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAACvAAAAAAATAMANIAAAAAAAAAAAAAAAAADAAAAAAQAVAMgNIAAAAAAAAAAAAAAAAADJAAAAAAATALgNIAAAAAAAAAAAAAAAAADcAAAAAAARAAgJAAAAAAAAAAAAAAAAAADvAAAAAQAWALgPIAAAAAAAAAAAAAAAAAAFAQAAEgAOAAAIAAAAAAAAAgAAAAAAAAAVAQAAIAAAAAAAAAAAAAAAAAAAAAAAAABtAQAAIAAXAAAQIAAAAAAAAAAAAAAAAAAxAQAAEAAXABAQIAAAAAAAAAAAAAAAAAAPAQAAEgAPAAQIAAAAAAAAAAAAAAAAAAA4AQAAEgAAAAAAAAAAAAAAAAAAAAAAAABMAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABrAQAAEAAXAAAQIAAAAAAAAAAAAAAAAAB4AQAAIAAAAAAAAAAAAAAAAAAAAAAAAACHAQAAEQIXAAgQIAAAAAAAAAAAAAAAAACUAQAAEQAQABAIAAAAAAAABAAAAAAAAACjAQAAEgAOAJAHAAAAAAAAZQAAAAAAAAC7AAAAEAAYABgQIAAAAAAAAAAAAAAAAABxAQAAEgAOAEAFAAAAAAAAKwAAAAAAAACzAQAAEAAYABAQIAAAAAAAAAAAAAAAAAC/AQAAEgAOAEoGAAAAAAAARgEAAAAAAADEAQAAEQIXABAQIAAAAAAAAAAAAAAAAADQAQAAIAAAAAAAAAAAAAAAAAAAAAAAAADqAQAAIgAAAAAAAAAAAAAAAAAAAAAAAACtAQAAEgALAPAEAAAAAAAAAAAAAAAAAAAAY3J0c3R1ZmYuYwBkZXJlZ2lzdGVyX3RtX2Nsb25lcwBfX2RvX2dsb2JhbF9kdG9yc19hdXgAY29tcGxldGVkLjc2OTgAX19kb19nbG9iYWxfZHRvcnNfYXV4X2ZpbmlfYXJyYXlfZW50cnkAZnJhbWVfZHVtbXkAX19mcmFtZV9kdW1teV9pbml0X2FycmF5X2VudHJ5AE1BWE1JTi5jAF9fRlJBTUVfRU5EX18AX19pbml0X2FycmF5X2VuZABfRFlOQU1JQwBfX2luaXRfYXJyYXlfc3RhcnQAX19HTlVfRUhfRlJBTUVfSERSAF9HTE9CQUxfT0ZGU0VUX1RBQkxFXwBfX2xpYmNfY3N1X2ZpbmkAX0lUTV9kZXJlZ2lzdGVyVE1DbG9uZVRhYmxlAF9lZGF0YQBwcmludGZAQEdMSUJDXzIuMi41AF9fbGliY19zdGFydF9tYWluQEBHTElCQ18yLjIuNQBfX2RhdGFfc3RhcnQAX19nbW9uX3N0YXJ0X18AX19kc29faGFuZGxlAF9JT19zdGRpbl91c2VkAF9fbGliY19jc3VfaW5pdABfX2Jzc19zdGFydABtYWluAF9fVE1DX0VORF9fAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19jeGFfZmluYWxpemVAQEdMSUJDXzIuMi41AAAuc3ltdGFiAC5zdHJ0YWIALnNoc3RydGFiAC5pbnRlcnAALm5vdGUuQUJJLXRhZwAubm90ZS5nbnUuYnVpbGQtaWQALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5keW5hbWljAC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAQAAAAIAAAAAAAAAOAIAAAAAAAA4AgAAAAAAABwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIwAAAAcAAAACAAAAAAAAAFQCAAAAAAAAVAIAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAADEAAAAHAAAAAgAAAAAAAAB0AgAAAAAAAHQCAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABEAAAA9v//bwIAAAAAAAAAmAIAAAAAAACYAgAAAAAAABwAAAAAAAAABQAAAAAAAAAIAAAAAAAAAAAAAAAAAAAATgAAAAsAAAACAAAAAAAAALgCAAAAAAAAuAIAAAAAAACoAAAAAAAAAAYAAAABAAAACAAAAAAAAAAYAAAAAAAAAFYAAAADAAAAAgAAAAAAAABgAwAAAAAAAGADAAAAAAAAhAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABeAAAA////bwIAAAAAAAAA5AMAAAAAAADkAwAAAAAAAA4AAAAAAAAABQAAAAAAAAACAAAAAAAAAAIAAAAAAAAAawAAAP7//28CAAAAAAAAAPgDAAAAAAAA+AMAAAAAAAAgAAAAAAAAAAYAAAABAAAACAAAAAAAAAAAAAAAAAAAAHoAAAAEAAAAAgAAAAAAAAAYBAAAAAAAABgEAAAAAAAAwAAAAAAAAAAFAAAAAAAAAAgAAAAAAAAAGAAAAAAAAACEAAAABAAAAEIAAAAAAAAA2AQAAAAAAADYBAAAAAAAABgAAAAAAAAABQAAABYAAAAIAAAAAAAAABgAAAAAAAAAjgAAAAEAAAAGAAAAAAAAAPAEAAAAAAAA8AQAAAAAAAAXAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIkAAAABAAAABgAAAAAAAAAQBQAAAAAAABAFAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACUAAAAAQAAAAYAAAAAAAAAMAUAAAAAAAAwBQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAnQAAAAEAAAAGAAAAAAAAAEAFAAAAAAAAQAUAAAAAAADCAgAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAKMAAAABAAAABgAAAAAAAAAECAAAAAAAAAQIAAAAAAAACQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACpAAAAAQAAAAIAAAAAAAAAEAgAAAAAAAAQCAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAsQAAAAEAAAACAAAAAAAAAAgJAAAAAAAACAkAAAAAAAA8AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAL8AAAABAAAAAgAAAAAAAABICQAAAAAAAEgJAAAAAAAACAEAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADJAAAADgAAAAMAAAAAAAAAuA0gAAAAAAC4DQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA1QAAAA8AAAADAAAAAAAAAMANIAAAAAAAwA0AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAOEAAAAGAAAAAwAAAAAAAADIDSAAAAAAAMgNAAAAAAAA8AEAAAAAAAAGAAAAAAAAAAgAAAAAAAAAEAAAAAAAAACYAAAAAQAAAAMAAAAAAAAAuA8gAAAAAAC4DwAAAAAAAEgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA6gAAAAEAAAADAAAAAAAAAAAQIAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAPAAAAAIAAAAAwAAAAAAAAAQECAAAAAAABAQAAAAAAAACAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD1AAAAAQAAADAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAACkAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAQBAAAAAAAADoBQAAAAAAABsAAAArAAAACAAAAAAAAAAYAAAAAAAAAAkAAAADAAAAAAAAAAAAAAAAAAAAAAAAACgWAAAAAAAABgIAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAuGAAAAAAAAP4AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"
	};
	int outlen = 0;
	FILE *fp = NULL;

	outlen = base64_decode(bbuf);

	fp = fopen("./bin", "w");
	fwrite(bbuf, outlen, 1, fp);
	fclose(fp);
	return 0;
}

